"""
TICKR — Nifty Index Universe Definitions
Symbol lists for NIFTY 50, NIFTY NEXT 50, NIFTY 500, NIFTY 1000.
"""

NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "BHARTIARTL", "ICICIBANK", "KOTAKBANK",
    "LT", "BAJFINANCE", "HINDUNILVR", "SBIN", "AXISBANK", "ASIANPAINT", "MARUTI",
    "TITAN", "NESTLEIND", "ULTRACEMCO", "TECHM", "POWERGRID", "NTPC", "WIPRO",
    "HCLTECH", "SUNPHARMA", "BAJAJFINSV", "TATAMOTORS", "ONGC", "JSWSTEEL",
    "TATASTEEL", "ADANIENT", "ADANIPORTS", "BPCL", "COALINDIA", "DIVISLAB",
    "DRREDDY", "EICHERMOT", "GRASIM", "HEROMOTOCO", "INDUSINDBK", "ITC",
    "CIPLA", "M&M", "BRITANNIA", "APOLLOHOSP", "HDFCLIFE", "SBILIFE",
    "TATACONSUM", "UPL", "VEDL", "SHREECEM", "BAJAJ-AUTO",
]

NIFTY_NEXT_50 = [
    "ABB", "ADANIGREEN", "ADANITRANS", "AMBUJACEM", "AUROPHARMA", "BANDHANBNK",
    "BERGEPAINT", "BIOCON", "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL",
    "CONCOR", "DABUR", "DLF", "GAIL", "GODREJCP", "GODREJPROP",
    "HAVELLS", "ICICIGI", "ICICIPRULI", "INDUSTOWER", "IRCTC", "LICI",
    "LUTION", "LUPIN", "MARICO", "MCDOWELL-N", "MUTHOOTFIN", "NAUKRI",
    "PAGEIND", "PETRONET", "PIDILITIND", "PNB", "RECLTD", "SAIL",
    "SIEMENS", "SRF", "TORNTPHARM", "TRENT", "TVSMOTOR", "UBL",
    "UNITDSPR", "VBL", "VOLTAS", "WHIRLPOOL", "ZYDUSLIFE", "ALKEM",
    "ASTRAL", "BALKRISIND",
]

# For brevity, NIFTY 500 and 1000 include the above + additional symbols
# In production, load from a CSV or Breeze API universe endpoint
NIFTY_500 = NIFTY_50 + NIFTY_NEXT_50 + [
    "ABCAPITAL", "ABFRL", "ACC", "AFFLE", "AIAENG", "AJANTPHARM",
    "ALEXIS", "APLLTD", "APTUS", "ATUL", "AUBANK", "AVANTIFEED",
    "BAJAJHLDNG", "BATAINDIA", "BEL", "BHEL", "BIRLASOFT", "BLUESTARCO",
    "BSOFT", "CAMS", "CANFINHOME", "CDSL", "CENTURYTEX", "CESC",
    "CLEAN", "COFORGE", "CROMPTON", "CUB", "CUMMINSIND", "DEEPAKNTR",
    "DELTACORP", "DMART", "ELGIEQUIP", "EMAMILTD", "ENGINERSIN",
    "EQUITASBNK", "ESCORTS", "EXIDEIND", "FINEORG", "FLUOROCHEM",
    "FORTIS", "GLAND", "GLAXO", "GNFC", "GRINDWELL", "GSPL",
    "GUJARATGAS", "HAPPSTMNDS", "HDFCAMC", "HFCL", "HONAUT",
]

NIFTY_1000 = NIFTY_500 + [
    # Additional mid/small cap stocks
    "IDFCFIRSTB", "IFCI", "IIFL", "INDIANB", "INDIGO", "IOB",
    "IPCALAB", "IRB", "IRFC", "JCHAC", "JKCEMENT", "JKLAKSHMI",
    "JKPAPER", "JMFINANCIL", "JSL", "JUBLFOOD", "JUBILANT",
    "JUSTDIAL", "KAJARIACER", "KALPATPOWR", "KANSAINER", "KARURVYSYA",
    "KEC", "KFINTECH", "KNRCON", "KRBL", "KSCL", "LALPATHLAB",
    "LAURUSLABS", "LICHSGFIN", "LINDEINDIA", "LTF", "LTTS",
    "MAHINDCIE", "MANAPPURAM", "MANKIND", "MAPRO", "MFSL",
    "MGLAMINES", "MIDHANI", "MMTC", "MRF", "MRPL", "NATIONALUM",
]

UNIVERSES = {
    "NIFTY 50": NIFTY_50,
    "NIFTY NEXT 50": NIFTY_NEXT_50,
    "NIFTY 500": NIFTY_500,
    "NIFTY 1000": NIFTY_1000,
}


def get_universe(name: str) -> list[str]:
    return UNIVERSES.get(name, NIFTY_50)


def list_universes() -> list[str]:
    return list(UNIVERSES.keys())
